### ISSUE TITLE
Android N - need to generate ca.crt (not ca.pem)

### ISSUE THREAD

**Issue by l3iggs** [rastapasta/pokemon-go-mitm#47]
The `ca.pem` provided here does not work for my android (n). I can get it to work by generating a `ca.crt` from your `ca.pem` like so:
```
openssl x509 -inform PEM -outform DM -in .http-mitm-proxy/certs/ca.pem -out .http-mitm-proxy/certs/ca.crt
```
but this requires the openssl binary which may not always be easy to come by. Could the project here directly generate the `ca.crt` that many of us need?
see: https://github.com/justinleewells/pogo-optimizer/pull/108

**Comment by rastapasta** [comment]
solved here https://github.com/joeferner/node-http-mitm-proxy/issues/96

**Comment by l3iggs** [comment]
This is not solved.
Where is the implementation? 
https://github.com/joeferner/node-http-mitm-proxy/issues/96 is a description of how this issue could be solved.

**Comment by rastapasta** [comment]
Yes, I meant the way how it could be fixed in the upstream library. It's an issue there, if you take a look at the code, we don't handle any certification generation directly. This is not a bug/issue that this project will fix. That's why I consider this issue as solved in context of this project. Cheers!

**Comment by rastapasta** [comment]
though... ok, it's still an open issue until there actually is a fix in the upstream lib. reopening.

**Comment by Poootaatoooo** [comment]
i installed the ca.pem using an app called "root certificate manager". Just open it, tap the folder icon, navigate to the ca.pem, and it'll install it.

**Comment by rastapasta** [comment]
Added advice in the instructions - thank's for your input! Cheers!
